### PR TITLE
UI Mocks for Authorization Username / Password Scenario.

### PR DESCRIPTION
**Pull request by rqc**
Created some simple mockups for the *end-to-end* flow for authentication (from a user's perspective). 

@edagan @gmatoshp @eitzhaki please review.

### CODE REVIEW

**Comment by edagan** [comment]
We have a UI/UX expert working on this. at this very minute. You seem to be aligned. 
Emailing this to her, please coordinate :)

**Comment by eitzhaki** [comment]
@rqc incase of success user need to replace "return to channel" button to "Close" that will close the window and that's all. I don't think we should handle the return to the original place (is it web or desketop, or if the user already changed channel)

**Comment by eitzhaki** [comment]
In the welcome page it would be better to replace the "save" button to "Send" or "Submit".

**Comment by rqc** [comment]
guys, I incorporated your suggestions and the changes are already in the [`master`](https://github.com/eedevops/he-design/blob/master/e2e_scenarios/mockups.md) branch. Please check them out! If you think it is good, let me know if I can close this pull request.

**Comment by edagan** [comment]
@rqc Please add the links to the mockups Michal Angel has provided.

**Comment by rqc** [comment]
Will track it down here: https://github.com/eedevops/he-design/issues/4

**Pull request closed without merging**
